#!/usr/bin/perl

use strict;

my $qm = '/usr/sbin/qm';
my $pct = '/usr/sbin/pct';
my $firewall_dir = "/etc/pve/firewall";
my $cp = '/bin/cp';

sub get_ids {
    my $cmd = shift;

    my @ids = map { /^\s*(\d+)\s+/ } grep { ! /^\s*vmid/i } `$cmd list`;

    return \@ids;
    }

sub is_firewall_template {
    my $cmd = shift;
    my $id = shift;
    
    my @lines = `$cmd config $id`;
    if (grep(/description.*firewall.*template/i, @lines)) { return 1; }
    
    return 0;
}

sub has_firewall {
    my $id = shift;
    
    return 1 if (-f "$firewall_dir/$id.fw");
    
    return 0;
}

sub copy_firewall {
    my $from_id = shift;
    my $to_id = shift;
    
    `$cp $firewall_dir/$from_id.fw $firewall_dir/$to_id.fw`;
}

sub main {
    my $ct_ids = get_ids($pct);
    my $vm_ids = get_ids($qm);
    my @all_ids = (@$ct_ids, @$vm_ids);
    
    # find firewall template
    
    # check through the containers
    my @ct_template_ids = grep { is_firewall_template($pct, $_) } @$ct_ids;
    my $fw_template_id = pop(@ct_template_ids);
    
    # check through the vms if we didn't find one in the containerss
    if (not defined $fw_template_id) {
	my @vm_template_ids = grep { is_firewall_template($qm, $_) } @$vm_ids;
	$fw_template_id = pop(@vm_template_ids);
    }
    
    die "no firewall templates found" if (not defined $fw_template_id);
    
    # find missing firewalls
    my @missing_firewalls = grep { not has_firewall($_) } @all_ids;
    
    # copy firewall template to vms/containers without firewall
    map { copy_firewall($fw_template_id, $_) } @missing_firewalls;
}

main();
