#!/bin/bash

export PATH="$PATH:/usr/bin:/bin"

#remove stuff from crontab
(crontab -l 2>/dev/null | grep -v proxmox_utils) | crontab -
(crontab -l 2>/dev/null | grep -v MAILTO) | crontab -

#add stuff to crontab
(echo 'MAILTO=""'; crontab -l 2>/dev/null) | crontab -
(crontab -l 2>/dev/null | grep -v command_marker_1; echo "31 0 * * * /root/utils/proxmox_utils/periodic_snapshots >/dev/null 2>&1 #command_marker_1") | crontab -
(crontab -l 2>/dev/null | grep -v command_marker_2; echo "31 1 * * * /root/utils/proxmox_utils/periodic_backups >/dev/null 2>&1   #command_marker_2") | crontab -
(crontab -l 2>/dev/null | grep -v command_marker_3; echo "*/5 * * * * /root/utils/proxmox_utils/firewall_template >/dev/null 2>&1 #command_marker_3") | crontab -
(crontab -l 2>/dev/null | grep -v command_marker_4; echo "0 0 * * * /root/utils/proxmox_utils/update >/dev/null 2>&1              #command_marker_4") | crontab -

#update myself
/usr/bin/git -C /root/utils/proxmox_utils pull
